name: ASTCxSAST
on:
  push:
   branches:
     - main
     - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx AST CLI Action
       uses: checkmarx/ast-github-action@main #Github Action version
       with:
         project_name: ${{ github.repository }}
         cx_tenant: nfr_trustdimension
         base_uri: https://ast.checkmarx.net
         cx_client_id: ${{ secrets.CLIENT_ID }}
         cx_client_secret: ${{ secrets.SECRET }}
         branch: ${{ github.ref }}
         additional_params:
          --threshold "sast-high=100; sast-medium=100; sca-high=100"
          --project-tags tag1,tag2,tag3
          --tags tag
          
     - name: Rapid7 InsightAppSec Scan
       uses: rapid7/insightappsec-scan-github-actions@v1.1.0
       with:
         region: "us"
         api-key: ${{ secrets.IAS_API_KEY }}
         scan-config-id: "699216b0-9578-4dcc-b02e-9aa315a4bc9a"
         vuln-query: "vulnerability.severity = 'HIGH'"
     - name: Upload findings
       if: always()
       run: echo "${{ steps.my-scan.outputs.scan-findings }}"

     - name: CheckmarxDAST
       uses: Checkmarx/dast-github-action@v1.0.0-beta
       env:
         CX_APIKEY: ${{ secrets.CX_ONE_API_KEY }}
       with:
        command: "web"
        config: './security_tweets.yaml'
        base_url: https://ast.checkmarx.net
        environment_id: "857f87e9-884d-48e6-9d30-ba0249ce6725"
