name: ASTCxSAST
on:
  push:
   branches:
     - main
     - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx AST CLI Action
       uses: checkmarx/ast-github-action@main #Github Action version
       with:
         project_name: ${{ github.repository }}
         cx_tenant: nfr_trustdimension
         base_uri: https://ast.checkmarx.net
         cx_client_id: ${{ secrets.CLIENT_ID }}
         cx_client_secret: ${{ secrets.SECRET }}
         branch: ${{ github.ref }}
         additional_params:
          --threshold "sast-high=100; sast-medium=100; sca-high=100"
          --project-tags tag1,tag2,tag3
          --tags tag
  scan:
        runs-on: ubuntu-latest
        steps:
          - id: my-scan
            uses: rapid7/insightappsec-scan-github-actions@v1.1.0
            with:
              region: "us"
              api-key: ${{ secrets.IAS_API_KEY }}
              scan-config-id: "6a8a7522-e581-4a23-bc4a-792580c59bdb"
              vuln-query: "vulnerability.severity = 'HIGH'"
          - name: Upload findings
            if: always()
            run: echo "${{ steps.my-scan.outputs.scan-findings }}"
