name: Generate containers-resolution.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-containers-resolution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR) (opcional)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull container image and resolve digest
        run: |
          IMAGE_NAME="ghcr.io/tu-usuario/tu-imagen:latest"
          IMAGE_DIGEST=$(docker pull $IMAGE_NAME | grep "Digest" | awk '{print $2}')
          echo "{ \"image\": \"$IMAGE_NAME@$IMAGE_DIGEST\" }" > containers-resolution.json

      - name: Save containers-resolution.json as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: containers-resolution
          path: containers-resolution.json

          run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add containers-resolution.json
           git commit -m "Update containers-resolution.json" || echo "No changes to commit"
           git push
