name: ASTCxSAST
on:
  push:
   branches:
     - main
     - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx AST CLI Action
       uses: checkmarx/ast-github-action@main #Github Action version
       with:
         project_name: ${{ github.repository }}
         cx_tenant: nfr_trustdimension
         base_uri: https://ast.checkmarx.net
         cx_client_id: ${{ secrets.CLIENT_ID }}
         cx_client_secret: ${{ secrets.SECRET }}
         branch: ${{ github.ref }}
         additional_params:
          --threshold "sast-high=100; sast-medium=100; sca-high=100"
          --project-tags tag1,tag2,tag3
          --tags tag

     - name: Checkmarx DAST
       uses: Checkmarx/dast-github-action@v1.0.0-beta
       env:
         CX_APIKEY: ${{ secrets.CX_ONE_API_KEY }}
       with:
        command: "web"
        config: './security_tweets.yaml'
        base_url: https://ast.checkmarx.net
        environment_id: "81fd9e39-9843-441d-bd86-d7d343eb06dc"
        verbose: true
     - uses: actions/upload-artifact@v3
       name: Upload Logs
       with:
        name: report
        path: ./output
          
     - name: Rapid7 InsightAppSec Scan
       uses: rapid7/insightappsec-scan-github-actions@v1.1.0
       with:
         region: "us"
         api-key: ${{ secrets.IAS_API_KEY }}
         scan-config-id: "6a8a7522-e581-4a23-bc4a-792580c59bdb"
         vuln-query: "vulnerability.severity = 'HIGH'"
     - name: Upload findings
       if: always()
       run: echo "${{ steps.my-scan.outputs.scan-findings }}"
