name: ASOE
on:
  pull_request:
   branches:
     - master
     - main
     - pr
     - pr2
     - pr3
     - pr4
     - pr5
     - 'releases/**'
     - pr6
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Checkmarx AST CLI Action
       uses: Checkmarx/ast-github-action@2.0.37
       with:
         project_name: ${{ github.repository }}
         cx_tenant: nfr_trustdimension
         base_uri: https://ast.checkmarx.net
         cx_client_id: ${{ secrets.CLIENT_ID }}
         cx_client_secret: ${{ secrets.SECRET }}
         if: github.event_name == 'pull_request'
         run: echo "Branch name is $GITHUB_HEAD_REF"
         #branch: ${{ github.ref/refs/heads/}}
